/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc1822UpgradeableSol from "./draft-IERC1822Upgradeable.sol";
export type { draftIerc1822UpgradeableSol };
export type { IERC1967Upgradeable } from "./IERC1967Upgradeable";
export type { IERC5267Upgradeable } from "./IERC5267Upgradeable";
