/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRetirementRecipient,
  IRetirementRecipientInterface,
} from "../../../contracts/interfaces/IRetirementRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "retiree",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "quantities",
        type: "uint256[]",
      },
    ],
    name: "onRetirement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRetirementRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): IRetirementRecipientInterface {
    return new utils.Interface(_abi) as IRetirementRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRetirementRecipient {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRetirementRecipient;
  }
}
