/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJasmineOracle,
  IJasmineOracleInterface,
} from "../../../../contracts/test/CrypticInterface.sol/IJasmineOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "encodedMetadata",
        type: "bytes",
      },
    ],
    name: "updateSeries",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJasmineOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IJasmineOracleInterface {
    return new Interface(_abi) as IJasmineOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IJasmineOracle {
    return new Contract(address, _abi, runner) as unknown as IJasmineOracle;
  }
}
