/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface CryticERC20ExternalHarnessInterface extends utils.Interface {
  functions: {
    "MAX_VINTAGE()": FunctionFragment;
    "MIN_VINTAGE()": FunctionFragment;
    "bridge()": FunctionFragment;
    "eat()": FunctionFragment;
    "feeBeneficiary()": FunctionFragment;
    "feeManager()": FunctionFragment;
    "frontHalfPool()": FunctionFragment;
    "mintEAT(address,uint256,uint40,uint32)": FunctionFragment;
    "mintJLT(address,uint256,uint256)": FunctionFragment;
    "minter()": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "poolFactory()": FunctionFragment;
    "poolImplementation()": FunctionFragment;
    "poolManager()": FunctionFragment;
    "retirementService()": FunctionFragment;
    "test_ERC20external_constantSupply()": FunctionFragment;
    "test_ERC20external_selfTransfer(uint256)": FunctionFragment;
    "test_ERC20external_selfTransferFrom(uint256)": FunctionFragment;
    "test_ERC20external_setAllowance(address,uint256)": FunctionFragment;
    "test_ERC20external_setAllowanceTwice(address,uint256)": FunctionFragment;
    "test_ERC20external_spendAllowanceAfterTransfer(address,uint256)": FunctionFragment;
    "test_ERC20external_transfer(address,uint256)": FunctionFragment;
    "test_ERC20external_transferFrom(address,uint256)": FunctionFragment;
    "test_ERC20external_transferFromMoreThanBalance(address)": FunctionFragment;
    "test_ERC20external_transferFromToZeroAddress(uint256)": FunctionFragment;
    "test_ERC20external_transferFromZeroAmount(address)": FunctionFragment;
    "test_ERC20external_transferMoreThanBalance(address)": FunctionFragment;
    "test_ERC20external_transferToZeroAddress()": FunctionFragment;
    "test_ERC20external_transferZeroAmount(address)": FunctionFragment;
    "test_ERC20external_userBalanceNotHigherThanSupply()": FunctionFragment;
    "test_ERC20external_userBalancesLessThanTotalSupply()": FunctionFragment;
    "test_ERC20external_zeroAddressBalance()": FunctionFragment;
    "test_deposit(uint256,uint256)": FunctionFragment;
    "test_invalid_deposit(uint256,uint40)": FunctionFragment;
    "test_retire(uint256)": FunctionFragment;
    "test_withdraw_any(uint256)": FunctionFragment;
    "test_withdraw_specific_batch(uint256,uint256)": FunctionFragment;
    "test_withdraw_specific_single(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_VINTAGE"
      | "MIN_VINTAGE"
      | "bridge"
      | "eat"
      | "feeBeneficiary"
      | "feeManager"
      | "frontHalfPool"
      | "mintEAT"
      | "mintJLT"
      | "minter"
      | "oracle"
      | "owner"
      | "poolFactory"
      | "poolImplementation"
      | "poolManager"
      | "retirementService"
      | "test_ERC20external_constantSupply"
      | "test_ERC20external_selfTransfer"
      | "test_ERC20external_selfTransferFrom"
      | "test_ERC20external_setAllowance"
      | "test_ERC20external_setAllowanceTwice"
      | "test_ERC20external_spendAllowanceAfterTransfer"
      | "test_ERC20external_transfer"
      | "test_ERC20external_transferFrom"
      | "test_ERC20external_transferFromMoreThanBalance"
      | "test_ERC20external_transferFromToZeroAddress"
      | "test_ERC20external_transferFromZeroAmount"
      | "test_ERC20external_transferMoreThanBalance"
      | "test_ERC20external_transferToZeroAddress"
      | "test_ERC20external_transferZeroAmount"
      | "test_ERC20external_userBalanceNotHigherThanSupply"
      | "test_ERC20external_userBalancesLessThanTotalSupply"
      | "test_ERC20external_zeroAddressBalance"
      | "test_deposit"
      | "test_invalid_deposit"
      | "test_retire"
      | "test_withdraw_any"
      | "test_withdraw_specific_batch"
      | "test_withdraw_specific_single"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_VINTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VINTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "eat", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeBeneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "frontHalfPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintEAT",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintJLT",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "minter", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retirementService",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_constantSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_selfTransfer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_selfTransferFrom",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_setAllowance",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_setAllowanceTwice",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_spendAllowanceAfterTransfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transfer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferFrom",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferFromMoreThanBalance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferFromToZeroAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferFromZeroAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferMoreThanBalance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferToZeroAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_transferZeroAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_userBalanceNotHigherThanSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_userBalancesLessThanTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_ERC20external_zeroAddressBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test_deposit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_invalid_deposit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_retire",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_withdraw_any",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_withdraw_specific_batch",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "test_withdraw_specific_single",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_VINTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VINTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "frontHalfPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintEAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintJLT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirementService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_constantSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_selfTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_selfTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_setAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_setAllowanceTwice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_spendAllowanceAfterTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferFromMoreThanBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferFromToZeroAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferFromZeroAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferMoreThanBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferToZeroAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_transferZeroAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_userBalanceNotHigherThanSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_userBalancesLessThanTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_ERC20external_zeroAddressBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_deposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_invalid_deposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_retire",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_withdraw_any",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_withdraw_specific_batch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "test_withdraw_specific_single",
    data: BytesLike
  ): Result;

  events: {
    "AssertEqFail(string)": EventFragment;
    "AssertFail(string)": EventFragment;
    "AssertGtFail(string)": EventFragment;
    "AssertGteFail(string)": EventFragment;
    "AssertLtFail(string)": EventFragment;
    "AssertLteFail(string)": EventFragment;
    "AssertNeqFail(string)": EventFragment;
    "LogAddress(string,address)": EventFragment;
    "LogString(string)": EventFragment;
    "LogUint256(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssertEqFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertGtFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertGteFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertLtFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertLteFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssertNeqFail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogString"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogUint256"): EventFragment;
}

export interface AssertEqFailEventObject {
  arg0: string;
}
export type AssertEqFailEvent = TypedEvent<[string], AssertEqFailEventObject>;

export type AssertEqFailEventFilter = TypedEventFilter<AssertEqFailEvent>;

export interface AssertFailEventObject {
  arg0: string;
}
export type AssertFailEvent = TypedEvent<[string], AssertFailEventObject>;

export type AssertFailEventFilter = TypedEventFilter<AssertFailEvent>;

export interface AssertGtFailEventObject {
  arg0: string;
}
export type AssertGtFailEvent = TypedEvent<[string], AssertGtFailEventObject>;

export type AssertGtFailEventFilter = TypedEventFilter<AssertGtFailEvent>;

export interface AssertGteFailEventObject {
  arg0: string;
}
export type AssertGteFailEvent = TypedEvent<[string], AssertGteFailEventObject>;

export type AssertGteFailEventFilter = TypedEventFilter<AssertGteFailEvent>;

export interface AssertLtFailEventObject {
  arg0: string;
}
export type AssertLtFailEvent = TypedEvent<[string], AssertLtFailEventObject>;

export type AssertLtFailEventFilter = TypedEventFilter<AssertLtFailEvent>;

export interface AssertLteFailEventObject {
  arg0: string;
}
export type AssertLteFailEvent = TypedEvent<[string], AssertLteFailEventObject>;

export type AssertLteFailEventFilter = TypedEventFilter<AssertLteFailEvent>;

export interface AssertNeqFailEventObject {
  arg0: string;
}
export type AssertNeqFailEvent = TypedEvent<[string], AssertNeqFailEventObject>;

export type AssertNeqFailEventFilter = TypedEventFilter<AssertNeqFailEvent>;

export interface LogAddressEventObject {
  arg0: string;
  arg1: string;
}
export type LogAddressEvent = TypedEvent<
  [string, string],
  LogAddressEventObject
>;

export type LogAddressEventFilter = TypedEventFilter<LogAddressEvent>;

export interface LogStringEventObject {
  arg0: string;
}
export type LogStringEvent = TypedEvent<[string], LogStringEventObject>;

export type LogStringEventFilter = TypedEventFilter<LogStringEvent>;

export interface LogUint256EventObject {
  arg0: string;
  arg1: BigNumber;
}
export type LogUint256Event = TypedEvent<
  [string, BigNumber],
  LogUint256EventObject
>;

export type LogUint256EventFilter = TypedEventFilter<LogUint256Event>;

export interface CryticERC20ExternalHarness extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CryticERC20ExternalHarnessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_VINTAGE(overrides?: CallOverrides): Promise<[number]>;

    MIN_VINTAGE(overrides?: CallOverrides): Promise<[number]>;

    bridge(overrides?: CallOverrides): Promise<[string]>;

    eat(overrides?: CallOverrides): Promise<[string]>;

    feeBeneficiary(overrides?: CallOverrides): Promise<[string]>;

    feeManager(overrides?: CallOverrides): Promise<[string]>;

    frontHalfPool(overrides?: CallOverrides): Promise<[string]>;

    mintEAT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      techType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintJLT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    minter(overrides?: CallOverrides): Promise<[string]>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    poolFactory(overrides?: CallOverrides): Promise<[string]>;

    poolImplementation(overrides?: CallOverrides): Promise<[string]>;

    poolManager(overrides?: CallOverrides): Promise<[string]>;

    retirementService(overrides?: CallOverrides): Promise<[string]>;

    test_ERC20external_constantSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_selfTransfer(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_selfTransferFrom(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_setAllowance(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_setAllowanceTwice(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_spendAllowanceAfterTransfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferFrom(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferFromMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferFromToZeroAddress(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferFromZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferToZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_transferZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_userBalanceNotHigherThanSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_userBalancesLessThanTotalSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_ERC20external_zeroAddressBalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_invalid_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_retire(
      retireAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_withdraw_any(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_withdraw_specific_batch(
      indexSeed: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    test_withdraw_specific_single(
      indexSeed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  MAX_VINTAGE(overrides?: CallOverrides): Promise<number>;

  MIN_VINTAGE(overrides?: CallOverrides): Promise<number>;

  bridge(overrides?: CallOverrides): Promise<string>;

  eat(overrides?: CallOverrides): Promise<string>;

  feeBeneficiary(overrides?: CallOverrides): Promise<string>;

  feeManager(overrides?: CallOverrides): Promise<string>;

  frontHalfPool(overrides?: CallOverrides): Promise<string>;

  mintEAT(
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    vintage: PromiseOrValue<BigNumberish>,
    techType: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintJLT(
    recipient: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    vintage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  minter(overrides?: CallOverrides): Promise<string>;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  poolFactory(overrides?: CallOverrides): Promise<string>;

  poolImplementation(overrides?: CallOverrides): Promise<string>;

  poolManager(overrides?: CallOverrides): Promise<string>;

  retirementService(overrides?: CallOverrides): Promise<string>;

  test_ERC20external_constantSupply(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_selfTransfer(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_selfTransferFrom(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_setAllowance(
    target: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_setAllowanceTwice(
    target: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_spendAllowanceAfterTransfer(
    target: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transfer(
    target: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferFrom(
    target: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferFromMoreThanBalance(
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferFromToZeroAddress(
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferFromZeroAmount(
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferMoreThanBalance(
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferToZeroAddress(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_transferZeroAmount(
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_userBalanceNotHigherThanSupply(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_userBalancesLessThanTotalSupply(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_ERC20external_zeroAddressBalance(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_deposit(
    mintAmount: PromiseOrValue<BigNumberish>,
    vintage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_invalid_deposit(
    mintAmount: PromiseOrValue<BigNumberish>,
    vintage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_retire(
    retireAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_withdraw_any(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_withdraw_specific_batch(
    indexSeed: PromiseOrValue<BigNumberish>,
    quantity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  test_withdraw_specific_single(
    indexSeed: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MAX_VINTAGE(overrides?: CallOverrides): Promise<number>;

    MIN_VINTAGE(overrides?: CallOverrides): Promise<number>;

    bridge(overrides?: CallOverrides): Promise<string>;

    eat(overrides?: CallOverrides): Promise<string>;

    feeBeneficiary(overrides?: CallOverrides): Promise<string>;

    feeManager(overrides?: CallOverrides): Promise<string>;

    frontHalfPool(overrides?: CallOverrides): Promise<string>;

    mintEAT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      techType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintJLT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    minter(overrides?: CallOverrides): Promise<string>;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    poolFactory(overrides?: CallOverrides): Promise<string>;

    poolImplementation(overrides?: CallOverrides): Promise<string>;

    poolManager(overrides?: CallOverrides): Promise<string>;

    retirementService(overrides?: CallOverrides): Promise<string>;

    test_ERC20external_constantSupply(overrides?: CallOverrides): Promise<void>;

    test_ERC20external_selfTransfer(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_selfTransferFrom(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_setAllowance(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_setAllowanceTwice(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_spendAllowanceAfterTransfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferFrom(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferFromMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferFromToZeroAddress(
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferFromZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferToZeroAddress(
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_transferZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_userBalanceNotHigherThanSupply(
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_userBalancesLessThanTotalSupply(
      overrides?: CallOverrides
    ): Promise<void>;

    test_ERC20external_zeroAddressBalance(
      overrides?: CallOverrides
    ): Promise<void>;

    test_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_invalid_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_retire(
      retireAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_withdraw_any(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_withdraw_specific_batch(
      indexSeed: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    test_withdraw_specific_single(
      indexSeed: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssertEqFail(string)"(arg0?: null): AssertEqFailEventFilter;
    AssertEqFail(arg0?: null): AssertEqFailEventFilter;

    "AssertFail(string)"(arg0?: null): AssertFailEventFilter;
    AssertFail(arg0?: null): AssertFailEventFilter;

    "AssertGtFail(string)"(arg0?: null): AssertGtFailEventFilter;
    AssertGtFail(arg0?: null): AssertGtFailEventFilter;

    "AssertGteFail(string)"(arg0?: null): AssertGteFailEventFilter;
    AssertGteFail(arg0?: null): AssertGteFailEventFilter;

    "AssertLtFail(string)"(arg0?: null): AssertLtFailEventFilter;
    AssertLtFail(arg0?: null): AssertLtFailEventFilter;

    "AssertLteFail(string)"(arg0?: null): AssertLteFailEventFilter;
    AssertLteFail(arg0?: null): AssertLteFailEventFilter;

    "AssertNeqFail(string)"(arg0?: null): AssertNeqFailEventFilter;
    AssertNeqFail(arg0?: null): AssertNeqFailEventFilter;

    "LogAddress(string,address)"(
      arg0?: null,
      arg1?: null
    ): LogAddressEventFilter;
    LogAddress(arg0?: null, arg1?: null): LogAddressEventFilter;

    "LogString(string)"(arg0?: null): LogStringEventFilter;
    LogString(arg0?: null): LogStringEventFilter;

    "LogUint256(string,uint256)"(
      arg0?: null,
      arg1?: null
    ): LogUint256EventFilter;
    LogUint256(arg0?: null, arg1?: null): LogUint256EventFilter;
  };

  estimateGas: {
    MAX_VINTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_VINTAGE(overrides?: CallOverrides): Promise<BigNumber>;

    bridge(overrides?: CallOverrides): Promise<BigNumber>;

    eat(overrides?: CallOverrides): Promise<BigNumber>;

    feeBeneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    feeManager(overrides?: CallOverrides): Promise<BigNumber>;

    frontHalfPool(overrides?: CallOverrides): Promise<BigNumber>;

    mintEAT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      techType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintJLT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    minter(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    poolFactory(overrides?: CallOverrides): Promise<BigNumber>;

    poolImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    poolManager(overrides?: CallOverrides): Promise<BigNumber>;

    retirementService(overrides?: CallOverrides): Promise<BigNumber>;

    test_ERC20external_constantSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_selfTransfer(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_selfTransferFrom(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_setAllowance(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_setAllowanceTwice(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_spendAllowanceAfterTransfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferFrom(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferFromMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferFromToZeroAddress(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferFromZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferToZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_transferZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_userBalanceNotHigherThanSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_userBalancesLessThanTotalSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_ERC20external_zeroAddressBalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_invalid_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_retire(
      retireAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_withdraw_any(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_withdraw_specific_batch(
      indexSeed: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    test_withdraw_specific_single(
      indexSeed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_VINTAGE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_VINTAGE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eat(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeBeneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    frontHalfPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintEAT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      techType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintJLT(
      recipient: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    minter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    retirementService(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    test_ERC20external_constantSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_selfTransfer(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_selfTransferFrom(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_setAllowance(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_setAllowanceTwice(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_spendAllowanceAfterTransfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transfer(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferFrom(
      target: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferFromMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferFromToZeroAddress(
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferFromZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferMoreThanBalance(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferToZeroAddress(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_transferZeroAmount(
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_userBalanceNotHigherThanSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_userBalancesLessThanTotalSupply(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_ERC20external_zeroAddressBalance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_invalid_deposit(
      mintAmount: PromiseOrValue<BigNumberish>,
      vintage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_retire(
      retireAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_withdraw_any(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_withdraw_specific_batch(
      indexSeed: PromiseOrValue<BigNumberish>,
      quantity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    test_withdraw_specific_single(
      indexSeed: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
