/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hevmSol from "./Hevm.sol";
export type { hevmSol };
import type * as propertiesHelperSol from "./PropertiesHelper.sol";
export type { propertiesHelperSol };
export type { IERC20 } from "./IERC20";
