/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc6093Sol from "./IERC6093.sol";
export type { ierc6093Sol };
export type { IERC1046 } from "./IERC1046";
