name: Fuzzing
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
    local-node:
      runs-on: [self-hosted, factory]
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      permissions:
        contents: read
        packages: read
      steps:
        - uses: actions/checkout@v3
        - name: Install packages
          uses: actions/setup-node@v3
          with:
            node-version: "18.15.0"
            cache: "yarn"
        - name: Install yarn
          run: npm install -g yarn
        - run: yarn install
          shell: bash
          env:
            NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        - name: Compile Contracts
          run: yarn run build:sol
        - name: Run Node
          run: yarn run start
          env:
            INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
    fuzz:
      runs-on: [self-hosted, factory]
      needs: [local-node]
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      permissions:
        contents: read
        packages: read
      steps:
        - uses: actions/checkout@v3
        - name: Install packages
          uses: actions/setup-node@v3
          with:
            node-version: "18.15.0"
            cache: "yarn"
        - name: Install yarn
          run: npm install -g yarn
        - run: yarn install
          shell: bash
          env:
            NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        - name: Compile Contracts
          run: yarn run build:sol
        - name: echidna-action
          uses: crytic/echidna-action@v2.0.2
          with:
            files: contracts/
            contract: ExternalJasminePoolTest
            config: echidna.config.yaml
          env:
            ECHIDNA_RPC_URL: "http://localhost:8545"
        
