name: lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  lint:
    runs-on: [self-hosted, factory]
    env:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'yarn'
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Compile Contracts
        run: yarn run build:sol
      - name: Run Lint
        run: yarn run lint
