name: lint
on:
  push:
    branches: 
      - main
      - dev
      - dev/*
  pull_request:
    branches:
      - main
      - dev
      - dev/*
  workflow_dispatch:
permissions:
  contents: read
  packages: read
jobs:
  lint:
    runs-on: [self-hosted, factory]
    env:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with private NPM package
        run: sed -i 's/GITHUB_TOKEN/ACTIONS_TOKEN/g' .npmrc
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Compile Contracts
        run: npm run build
      - name: Run Lint
        run: npm run lint
