name: Slither Analysis
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  analyze:
    runs-on: [self-hosted, factory]
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
        shell: bash
      - name: Run Slither
        id: slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: 'contracts'
          slither-args: '--solc-remaps "@openzeppelin/contracts=./node_modules/@openzeppelin/contracts hardhat=./node_modules/hardhat @jasmine-energy/contracts=./node_modules/@jasmine-energy/contracts @uniswap/v3-core/contracts=./node_modules/@uniswap/v3-core/contracts"'
          fail-on: 'none'
          sarif: results.sarif
          solc-version: '0.8.17'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
