name: Slither Analysis
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:
jobs:
  analyze:
    runs-on: [self-hosted, factory]
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
        shell: bash
      - name: Run Slither
        id: slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: 'contracts'
          slither-args: '--solc-remaps "@openzeppelin/contracts=./node_modules/@openzeppelin/contracts hardhat=./node_modules/hardhat @jasmine-energy/contracts=./node_modules/@jasmine-energy/contracts @uniswap/v3-core/contracts=./node_modules/@uniswap/v3-core/contracts" --checklist --checklist-limit 50 --exclude-dependencies --exclude-low --exclude-informational --exclude-optimization --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/'
          fail-on: 'none'
          solc-version: '0.8.20'
      - name: Create/update checklist as PR comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          SLITHER_OUTPUT: ${{ steps.slither.outputs.stdout }}
        with:
          script: |
            const script = require('.github/scripts/comment')
            const header = '# Slither report'
            const body = process.env.SLITHER_OUTPUT
            await script({ github, context, header, body })
